WIP disable mingwW64 for now
It causes evaluation errors on CI. While compiling GHC itself:
```
In file included from compiler/parser/cutils.c:6:0: error:

includes/Rts.h:29:10: error:
     fatal error: windows.h: No such file or directory
       29 | #include <windows.h>
          |          ^~~~~~~~~~~
   |
29 | #include <windows.h>
   |          ^
compilation terminated.
`cc' failed in phase `C Compiler'. (Exit code: 1)
```